### PR TITLE
Remove TX boundary from Event-based Gateway

### PR DESCRIPTION
**Pull request by falko**
and add TODO about Parallel/Inclusive Gateway with multiple incoming sequence flows

fixes https://github.com/camunda/camunda-modeler-plugins/issues/18

### CODE REVIEW

**Comment by ingorichtsmeier** [comment]
Hi Falko, as we use test driven development here, you should take care about the tests as well.

This line: https://github.com/bpmn-io/camunda-transaction-boundaries/blob/master/test/spec/TransactionBoundariesSpec.js#L122 breaks the build.

**Comment by falko** [comment]
Thx for the hint. Should be fixed now.

**Comment by pinussilvestrus** [comment]
Merged via 11e4179522c83de465d35b6a6e401c0ecaced2b9

**Comment by pinussilvestrus** [comment]
Regarding the `TODO`, could you maybe open an issue for that so that we are aware of that? @falko

**Pull request closed without merging**
